### ISSUE TITLE
Fallos al utilizar Peste devoradora con npc de bajo nivel

### ISSUE THREAD

**Issue by pangolp** [pangolp/chromiecraft-es#1]
### ¿Con qué cliente juegas?

esES

### Facción

- [ ] Alianza
- [X] Horda

### Fase de contenido

- [ ] Generico
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] Otro

### Comportamiento actual

Haciendo la mazmorra de Sima Ígnea con un amigo de nivel bajo, note que el debuff, no terminaba de completarse. En un principio, pensé que quizás algún otro npc, podría llegar a estar limpiándoles a los otros mobs, pero no. No detecte el error con otros de los hechizos de momento, los cuales si terminaban su tiempo con normalidad.

### Comportamiento esperado de Blizzlike

Creo que el spell debería de terminar con normalidad, dado que no debería de eliminarse el efecto antes de tiempo. Con la palabra de sombra: dolor por ejemplo, este problema no ocurre, y la misma cumple el tiempo completo.

### Fuente

- https://wowgaming.altervista.org/aowow/?spell=2944
- https://wowgaming.altervista.org/aowow/?spell=15317
- https://wowgaming.altervista.org/aowow/?zone=2437

### Pasos para reproducir el problema

1. Entrar a la mazmorra
2. Al menos al momento de ver el fallo, yo me encontraba en grupo
3. Tengas o no seleccionado al npc, el efecto desaparece antes de tiempo

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Sistema operativo

Ubuntu 20.04

### Modulos

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Personalizaciones

Ninguna

### Servidor

ChromieCraft

**Comment by JaboGamer** [comment]
Hello, me suena que Peste devoradora solo se puede aplicar a un enemigo, si lo aplicas a un segundo enemigo desaparece del primero. No estoy 100% seguro, lo reviso y comento.

**Comment by pangolp** [comment]
> Hello, me suena que Peste devoradora solo se puede aplicar a un enemigo, si lo aplicas a un segundo enemigo desaparece del primero. No estoy 100% seguro, lo reviso y comento.

Podría ser, la verdad yo tampoco estoy 100% seguro, pero este sistema de reporte y de debate en español, tiene como objetivo eso. Que podamos charlar, y sacar conclusiones, sobre determinadas mecánicas o dudas que nos surgen dentro del servidor. Porque si llega a ser un bug, el siguiente paso, ya seria crear el reporte en ingles, y compartirlo con el resto de la comunidad.

Lo de si es unit target, no me llamaría la atención, en el spell de momento no encontré información sobre eso. Pero en caso de ser así, entonces, tendría sentido que se le vaya el efecto. Por otro lado, la idea es que la gente pierda el miedo de reportar, que no tenga vergüenza. En caso de que no sea un error, se informa, y se cierra el tema. Pero necesitamos que participe un poco mas la comunidad, porque aun se encuentran algunas fallas en los niveles bajos que serian interesantes, que podamos pulir / mejorar aun mas.

**Comment by Nefertumm** [comment]
![image](https://user-images.githubusercontent.com/19627365/136068386-eb79f2e6-7f26-46a9-8bf8-4e2570249b0e.png)

Lo subrayado en rojo lo dice, solo puede afectar a un objetivo a la vez. 
Source: SpellWork con los dbcs de AzerothCore.
Procedo a cerrar.
