### ISSUE TITLE
[NPC Dungeon] Risen Aberration Scholomance Inmunidad a Holy damage

### ISSUE THREAD

**Issue by Veesha-The-Monkey** [pangolp/chromiecraft-es#10]
### ¿Con qué cliente juegas?

enUS

### Facción

- [X] Alianza
- [ ] Horda

### Fase de contenido

- [ ] Generico
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] Otro

### Comportamiento actual

Risen Aberration https://wowgaming.altervista.org/aowow/?npc=10485 es Totalmente inmune al daño magico

### Comportamiento esperado de Blizzlike

Inmune a GRAN parte del daño magico exceptuando daño Holy

https://wowgaming.altervista.org/aowow/?npc=10485

### Pasos para reproducir el problema

1.- Entrar a Scholomance
2.- Encontrar Risen Aberration
3.- Lanzar Consecration https://wowgaming.altervista.org/aowow/?spell=20923 , Exorcism https://wowgaming.altervista.org/aowow/?spell=10313 , Holy Shock https://wowgaming.altervista.org/aowow/?spell=25903 y ver la inmunidad

### Notas adicionales

En la tabla de Inmunidades mostrada en https://wowgaming.altervista.org/aowow/?npc=10485

Es inmune a todo excepto el daño Holy que no esta presente en la tabla, mi Teoría es que el daño holy lo toma como daño Radiant que es un equivalente a (Fire & Holy damage combinado) este es una subcategoria de tipos de magia, pero principalmente no deberia ser asi ya que el daño es en base al holy 

https://wowpedia.fandom.com/wiki/Magic_schools (No es de fiar al 100% pero siempre se ha sabido sobre las subcategorias) una pagina de guia en caso de que quieran saber mas de las escuelas de magia

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Sistema operativo

Ubuntu 20.04

### Modulos

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Personalizaciones

Ninguna

### Servidor

ChromieCraft

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/8415

**Comment by pangolp** [comment]
Excelente, parece que el reporte ya esta hecho en el repositorio de AzerothCore. Gracias @Veesha-The-Monkey por el reporte.
