### ISSUE TITLE
El soldado Hendel aparece en gris y no puedo interactuar con el

### ISSUE THREAD

**Issue by Storkell** [pangolp/chromiecraft-es#12]
### ¿Con qué cliente juegas?

esMX

### Facción

- [X] Alianza

### Fase de contenido

- [X] Generico

### Comportamiento actual

El Soldado hente aparece en gris y no puedo interactuar con el para continuar con la misión, el diplomático desaparecido 
![image](https://user-images.githubusercontent.com/104691712/166117156-19371689-1d61-49d1-a0f1-ab3733d5e76e.png)

### Comportamiento esperado de Blizzlike

deberia estar su nombre en verde para poder interactuar con el

### Pasos para reproducir el problema

recibir la misión de [Archimago Tervosh](https://es.classic.wowhead.com/npc=4967/archimago-tervosh)
entregar la misión al [Soldado Hendel](https://es.classic.wowhead.com/npc=4966/soldado-hendel)
![image](https://user-images.githubusercontent.com/104691712/166117134-5e48cc58-739a-4913-b3a1-84bb72c97d3b.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Sistema operativo

Ubuntu 20.04

### Modulos

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Personalizaciones

Ninguna

### Servidor

ChromieCraft

**Comment by pangolp** [comment]
Gracias por el reporte. En este momento me encuentro de viaje, pero ni bien regresé, trataré de acordarme para subirlo al repositorio oficial y si es posible lo voy a arreglar yo mismo. Te pido que si me olvidó, me recuerdes dejando un mensaje aquí.

**Comment by Storkell** [comment]
hola, estoy allí y el NPC se quedó atascado, un jugador de la Horda intentó matarlo, pero no funcionó

**Comment by pangolp** [comment]
Habrá que revisarlo. Seguramente tiene algún valor incorrecto y hace que falle. Pero si no estoy en mi máquina, no tengo forma de probarlo y hacer las pruebas que se necesitan.

**Comment by pangolp** [comment]
Para intentar entender un poco mejor el problema. Por lo que entiendo, el NPC si es atacado o entrada en combate, al parecer luego, es como que no se reinicia, y como que no vuelve a la normalidad ¿no?. En base a la foto, me da esa sensación. Sin embargo, estuve mirando el NPC por arriba, y le veo nada extraño. Pero tendré que averiguar mejor, una vez que llegue de viaje y tenga acceso a la computadora donde puedo hacer pruebas.

**Comment by Storkell** [comment]
pues al momento de tomar la captura de pantalla no se podía interactuar con el NPC, pero hace dos días fui a ver el NPC de nuevo y ya se le podía entregar la misión para continuar con la chain quest

**Comment by pangolp** [comment]
Ok, cerramos el tema entonces. Gracias por el reporte. Si se repite o encontras otro genial. Yo no tuve tiempo de verlo. Pero le comente a un amigo y quizás lo reviso el o fue algo random.
