### ISSUE TITLE
Gracina Poderespíritu, no se puede interactuar con ella

### ISSUE THREAD

**Issue by Storkell** [pangolp/chromiecraft-es#14]
### ¿Con qué cliente juegas?

esMX

### Facción

- [X] Alianza
- [ ] Horda

### Fase de contenido

- [X] Generico
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] Otro

### Comportamiento actual

No se puede interactuar con Gracina Poderespíritu para entregar las misiones
![image](https://user-images.githubusercontent.com/104691712/170893155-0e4f2853-040b-455d-8a53-07afa70a90fa.png)

### Comportamiento esperado de Blizzlike

se podria interactuar con Gracina Poderespíritu

### Pasos para reproducir el problema

completas las misiones "la sublevación de los silítidos" y "la calma que procede la tormenta"
no se puede interactuar con Gracina Poderespíritu

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Sistema operativo

Ubuntu 20.04

### Modulos

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Personalizaciones

Ninguna

### Servidor

ChromieCraft

**Comment by pangolp** [comment]
¿Por qué lo cerraste?

**Comment by Storkell** [comment]
el problema se soluciono cerrando y abriendo de nuevo el juego

**Comment by pangolp** [comment]
> el problema se soluciono cerrando y abriendo de nuevo el juego

Buenísimo entonces.
