### ISSUE TITLE
Botín de misiones al estar en grupo reducido / nulo

### ISSUE THREAD

**Issue by pangolp** [pangolp/chromiecraft-es#2]
### ¿Con qué cliente juegas?

esES

### Facción

- [ ] Alianza
- [X] Horda

### Fase de contenido

- [ ] Generico
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] Otro

### Comportamiento actual

Realizando misiones con un amigo, notamos que los npc no nos daban los items de quest, por lo que desarmamos el grupo y de esa forma, pudimos conseguirlo. Nota: mi amigo, tenia la misión completa cuando decidimos desarmar el grupo, y la probabilidad fue prácticamente del 80%.

### Comportamiento esperado de Blizzlike

Si uno de los 2, tiene completada la quest, por mas que estén en grupo, deberían de poder seguir completando la misión las demas personas sin la necesidad de que el drop se reduzca.

### Fuente

- https://wowgaming.altervista.org/aowow/?npc=1941
- https://wowgaming.altervista.org/aowow/?quest=358

### Pasos para reproducir el problema

1. Crear un grupo
2. Tener la misión tomada `.quest add 358`
3. Completarla, con alguno de los 2 personajes `.quest complete 358`
4. Intentar obtener el botín, con el jugador que todavia no tiene la misión con su compañero cerca.

### Notas adicionales

Una cosa que me olvide de aclarar, es que si el compañero no se encuentra dentro del radio de la otra persona, los objetos si eran obtenidos, nose si con la frecuencia que deberían, pero al menos con un poco mas de porcentaje.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Sistema operativo

Ubuntu 20.04

### Modulos

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Personalizaciones

Ninguna

### Servidor

ChromieCraft

**Comment by gary113** [comment]
Me pasó con una misión de Vallefresno llamada "La limpieza de Raene", en donde tienes que matar unas babosas las cuales dejan unos cofres de donde tienes que lotear un item llamado "Pomo de hierro". Yo completé la misión y luego mi amigo lo intentó, pero no le salía ni uno solo, eso que mató muchos, por lo que deshicimos el grupo, relogeó y recién le empezó salir dicho item.

Esta misión: https://wowgaming.altervista.org/aowow/?quest=1027

**Comment by pangolp** [comment]
Excelente. Ese ejemplo viene bien también para luego intentar reproducir el error.
